class CfgPatches
{
    /* Definitions */
    #include "\A3_Aegis\macros_urls.hpp"

	class A3_Revolucion_Characters_F_Revolucion
	{
		author = $STR_A3_A_BranFlakes;
		name = "Arma 3 Revolución - Characters and Clothing";
		url = linkRevolucion;
		requiredAddons[] =
		{
			A3_Aegis_Characters_F_Aegis,
			A3_Atlas_Characters_F_Atlas,
            A3_Revolucion_Data_F_Revolucion
		};
		requiredVersion = 0.1;
		units[] =
        {
            /* From "cfgBDF.hpp" */
			Rev_B_BDF_Soldier_A_F,
			Rev_B_BDF_soldier_AAA_F,
			Rev_B_BDF_soldier_AAR_F,
			Rev_B_BDF_Soldier_AR_F,
			Rev_B_BDF_Medic_F,
			Rev_B_BDF_Crew_F,
			Rev_B_BDF_Engineer_F,
			Rev_B_BDF_Soldier_Exp_F,
			Rev_B_BDF_Soldier_GL_F,
			Rev_B_BDF_Helipilot_F,
			Rev_B_BDF_Soldier_M_F,
			Rev_B_BDF_Officer_F,
			Rev_B_BDF_Soldier_F,
			Rev_B_BDF_soldier_AA_F,
			Rev_B_BDF_Soldier_AT_F,
			Rev_B_BDF_Soldier_SL_F,
			Rev_B_BDF_Soldier_TL_F,
			Rev_B_BDF_RadioOperator_F,
			Rev_B_BDF_Soldier_lite_F,
			Rev_B_BDF_Soldier_CQ_F,
			Rev_B_BDF_unarmed_F,
			Rev_B_BDF_Soldier_UAV_F,
			Rev_B_BDF_Pilot_F,
			Rev_B_BDF_Recon_AR_F,
			Rev_B_BDF_Recon_Exp_F,
			Rev_B_BDF_Recon_GL_F,
			Rev_B_BDF_Recon_JTAC_F,
			Rev_B_BDF_Recon_M_F,
			Rev_B_BDF_Recon_Medic_F,
			Rev_B_BDF_Recon_F,
			Rev_B_BDF_Recon_AT_F,
			Rev_B_BDF_Recon_LAT_F,
			Rev_B_BDF_Recon_TL_F,

            /* From "cfgFRR.hpp" */
			Rev_B_FRR_Soldier_A_F,
			Rev_B_FRR_Soldier_AR_F,
			Rev_B_FRR_Medic_F,
			Rev_B_FRR_Crew_F,
			Rev_B_FRR_Engineer_F,
			Rev_B_FRR_Soldier_Exp_F,
			Rev_B_FRR_Soldier_GL_F,
			Rev_B_FRR_Soldier_M_F,
			Rev_B_FRR_Officer_F,
			Rev_B_FRR_Soldier_F,
			Rev_B_FRR_Soldier_AT_F,
			Rev_B_FRR_Soldier_LAT_F,
			Rev_B_FRR_Soldier_SL_F,
			Rev_B_FRR_Soldier_TL_F,
			Rev_B_FRR_Soldier_lite_F,
			Rev_B_FRR_Soldier_CQ_F,
			Rev_B_FRR_Sharpshooter_F,
			Rev_B_FRR_Soldier_unarmed_F,
			Rev_B_FRR_Soldier_TechSpec_F,
			Rev_B_FRR_Story_El_Jefe,
			Rev_B_FRR_Story_El_Mula,
			Rev_B_FRR_Story_Diego,
			Rev_I_FRR_Soldier_A_F,
			Rev_I_FRR_Soldier_AR_F,
			Rev_I_FRR_Medic_F,
			Rev_I_FRR_Crew_F,
			Rev_I_FRR_Engineer_F,
			Rev_I_FRR_Soldier_Exp_F,
			Rev_I_FRR_Soldier_GL_F,
			Rev_I_FRR_Soldier_M_F,
			Rev_I_FRR_Officer_F,
			Rev_I_FRR_Soldier_F,
			Rev_I_FRR_Soldier_AT_F,
			Rev_I_FRR_Soldier_LAT_F,
			Rev_I_FRR_Soldier_SL_F,
			Rev_I_FRR_Soldier_TL_F,
			Rev_I_FRR_Soldier_lite_F,
			Rev_I_FRR_Soldier_CQ_F,
			Rev_I_FRR_Sharpshooter_F,
			Rev_I_FRR_Soldier_unarmed_F,
			Rev_I_FRR_Soldier_TechSpec_F,
			Rev_O_FRR_Soldier_A_F,
			Rev_O_FRR_Soldier_AR_F,
			Rev_O_FRR_Medic_F,
			Rev_O_FRR_Crew_F,
			Rev_O_FRR_Engineer_F,
			Rev_O_FRR_Soldier_Exp_F,
			Rev_O_FRR_Soldier_GL_F,
			Rev_O_FRR_Soldier_M_F,
			Rev_O_FRR_Officer_F,
			Rev_O_FRR_Soldier_F,
			Rev_O_FRR_Soldier_AT_F,
			Rev_O_FRR_Soldier_LAT_F,
			Rev_O_FRR_Soldier_SL_F,
			Rev_O_FRR_Soldier_TL_F,
			Rev_O_FRR_Soldier_lite_F,
			Rev_O_FRR_Soldier_CQ_F,
			Rev_O_FRR_Sharpshooter_F,
			Rev_O_FRR_Soldier_unarmed_F,
			Rev_O_FRR_Soldier_TechSpec_F,


            /* From "cfgCartels.hpp" */
			Rev_I_CDB_Soldier_Bandit_1_F,
			Rev_I_CDB_Soldier_Bandit_2_F,
			Rev_I_CDB_Soldier_Bandit_3_F,
			Rev_I_CDB_Soldier_Bandit_4_F,
			Rev_I_CDB_Soldier_Bandit_5_F,
			Rev_I_CDB_Soldier_Bandit_6_F,
			Rev_I_CDB_Soldier_Bandit_7_F,
			Rev_I_CDB_Soldier_Bandit_8_F,
			Rev_I_CDB_Soldier_Bandit_SG_F,
			Rev_I_CDB_Soldier_Bandit_M_F,
			Rev_I_CDB_Soldier_Bandit_SMG_F,
			Rev_I_CDB_Soldier_Bandit_lite_F,
			Rev_I_CDB_Soldier_Pilot_F,
			Rev_I_CDB_Soldier_Bandit_Officer_F,
			Rev_I_CDB_Soldier_Para_F,
			Rev_I_CDB_Soldier_Para_TL_F,
			Rev_I_CDB_Soldier_Para_GL_F,
			Rev_I_CDB_Soldier_Para_Medic_F,
			Rev_I_CDB_Soldier_Para_AR_F,
			Rev_I_CDB_Soldier_Para_AT_F,
			Rev_I_CDB_Soldier_Para_M_F,
			Rev_I_CDB_Soldier_Drug_Lord_F,

            /* From "cfgFASR.hpp" */
			Rev_O_FASR_Soldier_A_F,
			Rev_O_FASR_Soldier_AR_F,
			Rev_O_FASR_Medic_F,
			Rev_O_FASR_Crew_F,
			Rev_O_FASR_Engineer_F,
			Rev_O_FASR_Soldier_Exp_F,
			Rev_O_FASR_Soldier_GL_F,
			Rev_O_FASR_Helipilot_F,
			Rev_O_FASR_Soldier_M_F,
			Rev_O_FASR_Officer_F,
			Rev_O_FASR_Soldier_F,
			Rev_O_FASR_Soldier_AT_F,
			Rev_O_FASR_Soldier_SL_F,
			Rev_O_FASR_Soldier_TL_F,
			Rev_O_FASR_RadioOperator_F,
			Rev_O_FASR_Soldier_lite_F,
			Rev_O_FASR_Soldier_CQ_F,
			Rev_O_FASR_Soldier_universal_F,
			Rev_O_FASR_unarmed_F,

			/* From "cfgPNB.hpp" */
			Rev_B_PNB_Soldier_AR_F,
			Rev_B_PNB_Soldier_Exp_F,
			Rev_B_PNB_Soldier_M_F,
			Rev_B_PNB_Commander_F,
			Rev_B_PNB_Soldier_F,
			Rev_B_PNB_Soldier_LAT_F,
			Rev_B_PNB_Soldier_Rifle_F,
			Rev_B_PNB_Soldier_SG_F,
			Rev_O_PNB_Soldier_AR_F,
			Rev_O_PNB_Soldier_Exp_F,
			Rev_O_PNB_Soldier_M_F,
			Rev_O_PNB_Commander_F,
			Rev_O_PNB_Soldier_F,
			Rev_O_PNB_Soldier_LAT_F,
			Rev_O_PNB_Soldier_Rifle_F,
			Rev_O_PNB_Soldier_SG_F,

			/* From "cfgVenezuela.hpp" */
			Rev_O_VZ_Soldier_F,
			Rev_O_VZ_TL_F,
			Rev_O_VZ_GL_F,
			Rev_O_VZ_AR_F,
			Rev_O_VZ_exp_F,
			Rev_O_VZ_M_F,
			Rev_O_VZ_medic_F,
			Rev_O_VZ_Soldier_LAT_F,
			Rev_O_VZ_A_F,
			Rev_O_VZ_Soldier_AAR_F,
			Rev_O_VZ_support_MG_F,
			Rev_O_VZ_support_AMG_F,
			Rev_O_VZ_support_Mort_F,
			Rev_O_VZ_support_AMort_F,
			Rev_O_VZ_support_AHAT_F,
			Rev_O_VZ_support_AAA_F,
			Rev_O_VZ_support_AAT_F,
			Rev_O_VZ_Crew_F,
			Rev_O_VZ_engineer_F,
			Rev_O_VZ_soldier_mine_F,
			Rev_O_VZ_Helipilot_F,
			Rev_O_VZ_Helicrew_F,
			Rev_O_VZ_Soldier_AA_F,
			Rev_O_VZ_Soldier_AT_F,
			Rev_O_VZ_Officer_F,
			Rev_O_VZ_Soldier_lite_F,
			Rev_O_VZ_SL_F,
			Rev_O_VZ_RadioOperator_F,
			Rev_O_VZ_Soldier_unarmed_F,
			Rev_O_VZ_survivor_F,
			Rev_O_VZ_Recon_F,
			Rev_O_VZ_recon_TL_F,
			Rev_O_VZ_recon_exp_F,
			Rev_O_VZ_recon_AR_F,
			Rev_O_VZ_recon_M_F,
			Rev_O_VZ_recon_medic_F,
			Rev_O_VZ_recon_GL_F,
			Rev_O_VZ_recon_LAT_F,
			Rev_O_VZ_recon_JTAC_F,
			Rev_O_VZ_Fighter_Pilot_F
        };
		weapons[] = {/* Automated */};
	};
};